<<<<<<< HEAD
# Generated by Django 6.0.4 on 2026-04-16 16:29
=======
# Generated by Django 6.0.4 on 2026-04-16 22:18
>>>>>>> 3537f8936b8f3a935e311e009c49fd1a0680838d

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateur', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('est_admin', models.BooleanField(default=False)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
