# Generated by Django 6.0.4 on 2026-04-16 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='est_admin',
            new_name='is_staff',
        ),
    ]
