# Generated by Django 6.0.4 on 2026-04-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panier',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
