# Generated by Django 6.0.4 on 2026-05-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_panier_date_debut_panier_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepanier',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlepanier',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
