# Generated by Django 6.0.4 on 2026-04-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='adresse',
        ),
        migrations.AddField(
            model_name='commande',
            name='paiement',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='commande',
            name='remarque',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='commande',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
