<<<<<<< HEAD
# Generated by Django 6.0.4 on 2026-04-16 16:29
=======
# Generated by Django 6.0.4 on 2026-04-16 22:18
>>>>>>> 3537f8936b8f3a935e311e009c49fd1a0680838d

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.PositiveIntegerField()),
                ('transmission', models.CharField(max_length=50)),
                ('description', models.TextField()),
<<<<<<< HEAD
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(null=True, upload_to='products/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
=======
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='voitures/')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voitures', to='products.category')),
>>>>>>> 3537f8936b8f3a935e311e009c49fd1a0680838d
            ],
        ),
    ]
