# Generated by Django 6.0.4 on 2026-04-25 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.PositiveIntegerField()),
                ('transmission', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('image_exterieur', models.ImageField(upload_to='voitures/exterieur/')),
                ('image_interieur', models.ImageField(upload_to='voitures/interieur/')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voitures', to='products.category')),
            ],
        ),
    ]
