# Generated by Django 6.0.4 on 2026-04-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='image_exterieur',
            field=models.ImageField(max_length=500, upload_to='voitures/exterieur/'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='image_interieur',
            field=models.ImageField(max_length=500, upload_to='voitures/interieur/'),
        ),
    ]
